@baseUrl = http://10.121.142.3:4567/

#############################################

POST {{baseUrl}}usuario/login
content-type: application/json

{
    "correo": "juan.perez@example.com",
    "contrasena": "1234pass"
}

#############################################

POST {{baseUrl}}usuario/validar
content-type: application/json

{
    "correo": "maria.gomez@example.com"
}

#############################################

POST {{baseUrl}}usuario/registro
Content-Type: application/x-www-form-urlencoded

nombres=Fermin&apellidos=Bernales&fecha_nacimiento=10/06/2000&correo=fermin.ber@example.com&celular=123456789&contrasena=1234pass&altura=1.70&peso=70&sexo=M&condiciones_medicas=Miopia